In [1]:
import polars

In [2]:
table = polars.read_excel(
    "https://cdn.bancentral.gov.do/documents/estadisticas/mercado-cambiario/documents/TASAS_CONVERTIBLES_OTRAS_MONEDAS.xlsx",
    read_options={
        "header_row": 2,

    })

Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 17, falling back to string

In [3]:
table.tail()

shape: (5, 18)
┌──────┬─────┬─────┬─────────────┬───┬──────────┬──────────────┬──────────────────────┬────────────┐
│ Año  ┆ Mes ┆ Día ┆ DOLAR       ┆ … ┆ LIBRA    ┆ CORONA SUECA ┆ DOLAR ESTADOUNIDENSE ┆ *BOLIVAR   │
│ ---  ┆ --- ┆ --- ┆ AUSTRALIANO ┆   ┆ ESCOCESA ┆ ---          ┆ ---                  ┆ FUERTE     │
│ i64  ┆ str ┆ i64 ┆ ---         ┆   ┆ ---      ┆ f64          ┆ f64                  ┆ VENEZOLANO │
│      ┆     ┆     ┆ str         ┆   ┆ f64      ┆              ┆                      ┆ ---        │
│      ┆     ┆     ┆             ┆   ┆          ┆              ┆                      ┆ str        │
╞══════╪═════╪═════╪═════════════╪═══╪══════════╪══════════════╪══════════════════════╪════════════╡
│ 2026 ┆ Abr ┆ 21  ┆ 42.5759     ┆ … ┆ 80.2651  ┆ 6.5038       ┆ 59.4138              ┆ 0.1242     │
│ 2026 ┆ Abr ┆ 22  ┆ 42.5727     ┆ … ┆ 80.2705  ┆ 6.4649       ┆ 59.3761              ┆ 0.124      │
│ 2026 ┆ Abr ┆ 23  ┆ 42.3835     ┆ … ┆ 79.883   ┆ 6.4262       ┆ 59.2362              ┆ 0.1236     │
│ 2026 ┆ Abr ┆ 24  ┆ 42.0387     ┆ … ┆ 79.5657  ┆ 6.3839       ┆ 58.9769              ┆ 0.123      │
│ 2026 ┆ Abr ┆ 27  ┆ 42.1181     ┆ … ┆ 79.8519  ┆ 6.384        ┆ 58.89                ┆ 0.1228     │
└──────┴─────┴─────┴─────────────┴───┴──────────┴──────────────┴──────────────────────┴────────────┘

In [4]:
# set all not date columns to float
cols_to_convert = [col for col in table.columns if col not in ["Año", "Mes", "Día"]]
table = table.with_columns([polars.col(col).cast(polars.Float64) for col in cols_to_convert])

In [5]:
table.tail()

shape: (5, 18)
┌──────┬─────┬─────┬─────────────┬───┬──────────┬──────────────┬──────────────────────┬────────────┐
│ Año  ┆ Mes ┆ Día ┆ DOLAR       ┆ … ┆ LIBRA    ┆ CORONA SUECA ┆ DOLAR ESTADOUNIDENSE ┆ *BOLIVAR   │
│ ---  ┆ --- ┆ --- ┆ AUSTRALIANO ┆   ┆ ESCOCESA ┆ ---          ┆ ---                  ┆ FUERTE     │
│ i64  ┆ str ┆ i64 ┆ ---         ┆   ┆ ---      ┆ f64          ┆ f64                  ┆ VENEZOLANO │
│      ┆     ┆     ┆ f64         ┆   ┆ f64      ┆              ┆                      ┆ ---        │
│      ┆     ┆     ┆             ┆   ┆          ┆              ┆                      ┆ f64        │
╞══════╪═════╪═════╪═════════════╪═══╪══════════╪══════════════╪══════════════════════╪════════════╡
│ 2026 ┆ Abr ┆ 21  ┆ 42.5759     ┆ … ┆ 80.2651  ┆ 6.5038       ┆ 59.4138              ┆ 0.1242     │
│ 2026 ┆ Abr ┆ 22  ┆ 42.5727     ┆ … ┆ 80.2705  ┆ 6.4649       ┆ 59.3761              ┆ 0.124      │
│ 2026 ┆ Abr ┆ 23  ┆ 42.3835     ┆ … ┆ 79.883   ┆ 6.4262       ┆ 59.2362              ┆ 0.1236     │
│ 2026 ┆ Abr ┆ 24  ┆ 42.0387     ┆ … ┆ 79.5657  ┆ 6.3839       ┆ 58.9769              ┆ 0.123      │
│ 2026 ┆ Abr ┆ 27  ┆ 42.1181     ┆ … ┆ 79.8519  ┆ 6.384        ┆ 58.89                ┆ 0.1228     │
└──────┴─────┴─────┴─────────────┴───┴──────────┴──────────────┴──────────────────────┴────────────┘

In [6]:
long_table = table.unpivot(
    index=["Año", "Mes", "Día"],
    variable_name="Moneda",
    value_name="rate_value",
)
long_table.shape

(83895, 5)

In [7]:
long_table.tail()

shape: (5, 5)
┌──────┬─────┬─────┬────────────────────────────┬────────────┐
│ Año  ┆ Mes ┆ Día ┆ Moneda                     ┆ rate_value │
│ ---  ┆ --- ┆ --- ┆ ---                        ┆ ---        │
│ i64  ┆ str ┆ i64 ┆ str                        ┆ f64        │
╞══════╪═════╪═════╪════════════════════════════╪════════════╡
│ 2026 ┆ Abr ┆ 21  ┆ *BOLIVAR FUERTE VENEZOLANO ┆ 0.1242     │
│ 2026 ┆ Abr ┆ 22  ┆ *BOLIVAR FUERTE VENEZOLANO ┆ 0.124      │
│ 2026 ┆ Abr ┆ 23  ┆ *BOLIVAR FUERTE VENEZOLANO ┆ 0.1236     │
│ 2026 ┆ Abr ┆ 24  ┆ *BOLIVAR FUERTE VENEZOLANO ┆ 0.123      │
│ 2026 ┆ Abr ┆ 27  ┆ *BOLIVAR FUERTE VENEZOLANO ┆ 0.1228     │
└──────┴─────┴─────┴────────────────────────────┴────────────┘

In [9]:
long_table = long_table.filter(polars.col("rate_value").is_not_null()).sort(["Año", "Mes", "Día"])
long_table.shape

(72073, 5)

In [10]:
long_table.tail()

shape: (5, 5)
┌──────┬─────┬─────┬──────────────────┬────────────┐
│ Año  ┆ Mes ┆ Día ┆ Moneda           ┆ rate_value │
│ ---  ┆ --- ┆ --- ┆ ---              ┆ ---        │
│ i64  ┆ str ┆ i64 ┆ str              ┆ f64        │
╞══════╪═════╪═════╪══════════════════╪════════════╡
│ 2026 ┆ Mar ┆ 31  ┆ YUAN CHINO       ┆ 8.7242     │
│ 2026 ┆ Mar ┆ 31  ┆ FRANCO SUIZO     ┆ 75.225     │
│ 2026 ┆ Mar ┆ 31  ┆ DOLAR CANADIENSE ┆ 43.2681    │
│ 2026 ┆ Mar ┆ 31  ┆ CORONA SUECA     ┆ 6.3311     │
│ 2026 ┆ Mar ┆ 31  ┆ REAL BRASILENO   ┆ 11.5107    │
└──────┴─────┴─────┴──────────────────┴────────────┘